server:
  port: 8182

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8910/user

spring:
  application:
    name: car-service
  datasource:
    url: jdbc:mysql://localhost:3306/share_a_ride?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: root
    password: admin123
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
