server:
  port: 8910

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/share_a_ride_2?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: root
    password: admin123
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

check-user-scopes: true